#!/bin/sh

set -e

function_name="aoyama-lambda-phantomjs-font"

name=$(basename $(pwd))

echo "name = [$name]"

rm -f "$name.zip"

zip -r "$name.zip" ./*

aws s3 cp "$name.zip" s3://aoyama.vallab.ninja/

aws lambda update-function-code --function-name "$function_name" --s3-bucket aoyama.vallab.ninja --s3-key "$name.zip" --publish --region ap-northeast-1
