#!/bin/sh

set -eu

echo "function_name = [$function_name]"

zip_path="$function_name.zip"

rm -f "$zip_path"

zip -r "$zip_path" ./*

aws lambda update-function-code --function-name "$function_name" --zip-file "fileb://${zip_path}" --publish
