#!/bin/sh

set -eu

echo "function_name = [$function_name]"
echo "bucket_name   = [$bucket_name]"
echo "region        = [$region]"

name=$(basename $(pwd))

echo "name = [$name]"

rm -f "$name.zip"

zip -r "$name.zip" ./*

aws s3 cp "$name.zip" s3://${bucket_name}/

aws lambda update-function-code --function-name "$function_name" --s3-bucket $bucket_name --s3-key "$name.zip" --publish --region ap-northeast-1
